### ISSUE TITLE
Cannot find module @actions/exec

### ISSUE THREAD

**Issue by KulkarniSuraj** [Pika1998/express-autodocs#12]
**Description**
Error occurs when `npm run dev` is run

**To Reproduce**
1. Go to 'express-autodocs'
2. `npm install`
3. `npm run dev`
4. `Error:  Cannot find module 'express-autodocs\node_modules\@actions\exec\lib\exec.js'. Please verify that the package.json has a valid "main" entry`

**Expected behavior**
Docs should be generated in output folder

**Screenshots**

**Desktop:**
 - OS: Windows 10

**Additional context**
The error is caused due to first line in [helpers/templateHelpers/createDocs.js](https://github.com/Pika1998/express-autodocs/blob/master/helpers/templateHelpers/createDocs.js) which isn't used anyway

The error is solved by removing this line

**Comment by KulkarniSuraj** [comment]
If possible I would like to work on code refactoring of this project

**Comment by Pika1998** [comment]
Sure you can send in a PR after removing that line, I will merge it😁

**Comment by KulkarniSuraj** [comment]
can you point me to some resources to learn how github actions work
I am also learning about rest apis and don't have a lot of experience with node.js. 'express' in particular

**Comment by Pika1998** [comment]
Ok sure, basically GitHub actions runs a specific program on events like Pull, Push, Etc

There are two main files one is the *action.yml* which defines what the action does, what input it takes, what steps it runs etc (this is the file you will find in this repo)

Then there is a workflow file (generally main.yml) which is used by other repositories to integrate multiple actions in their workflow

REST APIs are basically backend services which can be called by other third parties ( like if you want to interact with a database, it would be better if you have a backend service which does that for you , instead of directly writing the code in front end) **express allows to write such services which can be called by users**


Here are some resources which will help you in detail about this

1.[Creating your own JavaScript action](https://docs.github.com/en/free-pro-team@latest/actions/creating-actions/creating-a-javascript-action)

2. [Introduction to backend APIs](https://dev.to/cesareferrari/back-end-api-development-introduction-d57)

3. [understanding express is](https://dev.to/mikitashah/let-s-understand-the-express-js-framework-3j5n)

**Comment by KulkarniSuraj** [comment]
> Sure you can send in a PR after removing that line, I will merge it😁

Thanks for letting me work on this project 😃 
I will be working on making code **modular** and **optimized**

**Comment by Pika1998** [comment]
Sure thank you 😇

**Comment by Pika1998** [comment]
This issue has been resolved thanks to @KulkarniSuraj 
Check PR #13 for more details
